version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: PbqA9Blq3ICC
      POSTGRES_USER: teste_pratico_user
      POSTGRES_DB: teste_pratico_db
    ports:
      - "5432:5432"

  server:
    command: sh -c "adonis migration:run && adonis seed && npm run serve:dev"
    depends_on:
      - db
    build: .
    restart: always
    links:
      - db
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
