version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: PbqA9Blq3ICC
      POSTGRES_USER: teste_pratico_user
      POSTGRES_DB: teste_pratico_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  server:
    command: sh -c "adonis migration:run --force && adonis seed --force && adonis serve"
    depends_on:
      - db
    build: .
    restart: always
    links:
      - db
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
